name: 'drill4j-report-github-action'
description: 'Report test-coverage by Drill4J'
branding:
  icon: info
  color: blue
inputs:
  who-to-greet:
    description: 'Hello World PR comment'
    required: true
  repo-token:
    description: 'Github Token'
    required: true
runs:
  using: 'docker'
  image: './Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
    - ${{ inputs.repo-token }}
