name: 'drill4j-report-github-action'
description: 'Report test-coverage by Drill4J'
branding:
  icon: info
  color: blue
inputs:
  groupId:
    description: "Group ID"
    required: true
  agentId:
    description: "Agent ID"
    required: true
  currentBranch:
    description: "Current branch"
    required: true
  currentVcsRef:
    description: "Current VCS reference"
    required: true
  baseBranch:
    description: "Base branch"
    required: true
  baseVcsRef:
    description: "Base VCS reference"
    required: true
  drillHost:
    description: "Host of Drill admin"
    required: true
  drillPort:
    description: "Port of Drill admin"
    required: true
  repoToken:
    description: "Github Token"
    required: true
runs:
  using: 'docker'
  image: './Dockerfile'
