name: 'drill4j-report-github-action'
description: 'Hello World'
inputs:
  who-to-greet:
    description: 'Hello World PR comment'
    required: true
    default: 'World'
runs:
  using: 'docker'
  image: './docker/Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
